version: 2.1

workflows:
  main:
    jobs:
      - build:
          version: 12
          name: "Build (Node 12)"
      - lint:
          version: 12
          name: "Lint (Node 12)"
      - unit-tests:
          version: 8
          name: "Unit (Node 8)"
      - unit-tests:
          version: 10
          name: "Unit (Node 10)"
      - unit-tests:
          version: 12
          name: "Unit (Node 12)"
      - integration-tests:
          version: 8
          name: "Integration (Node 8)"
      - integration-tests:
          version: 10
          name: "Integration (Node 10)"
      - integration-tests:
          version: 12
          name: "Integration (Node 12)"
      - server-integration-tests:
          version: 12
          name: "Server Integration (Node 12)"

jobs:
  build:
    parameters:
      version:
        type: integer
    docker:
      - image: circleci/node:<< parameters.version >>
    steps:
      - checkout
      - run:
          name: "Build (Node << parameters.version >>)"
          command: |
            npm install
            npm run build

  lint:
    parameters:
      version:
        type: integer
    docker:
      - image: circleci/node:<< parameters.version >>
    steps:
      - checkout
      - run:
          name: "Lint (Node << parameters.version >>)"
          command: |
            npm install
            npm run lint

  integration-tests:
    parameters:
      version:
        type: integer
    docker:
      - image: circleci/node:<< parameters.version >>
    steps:
      - checkout
      - run:
          name: "Integration Tests (Node << parameters.version >>)"
          command: |
            npm install
            npm run integration

  server-integration-tests:
    parameters:
      version:
        type: integer
    docker:
      - image: circleci/node:<< parameters.version >>
    steps:
      - checkout
      - run:
          name: "Integration Tests (Node << parameters.version >>)"
          command: |
            npm install
            npm run server-integration

  unit-tests:
    parameters:
      version:
        type: integer
    docker:
      - image: circleci/node:<< parameters.version >>
    steps:
      - checkout
      - run:
          name: "Unit Tests (Node << parameters.version >>)"
          command: |
            npm install
            npm run unit
